version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  frontend:
    build: frontend
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    command: npm run dev -- --host 0.0.0.0
  backend:
    build: .
    environment:
      - ENVIRONMENT=dev
      - DATABASE_URL=postgres://postgres@db/postgres
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://jaeger:6831
    volumes:
      - type: bind
        source: ./config.docker-dev.yml
        target: /config.dev.yml
    ports:
      - "8080:8080"
    depends_on:
      - db
      - frontend
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      # web ui
      - "16686:16686"
      - "6831:6831/udp"
