### Login
POST {{base_url}}/api/login
Content-Type: application/json

{
  "username": "nikita",
  "name": "DCNick3"
}

### Get my profile
GET {{base_url}}/api/me

### Raise a 500 error
GET {{base_url}}/api/error

### Bad Request
POST {{base_url}}/api/login
Content-Type: application/json

{ "bad": "request" }

### Create a session
POST {{base_url}}/api/sessions
Content-Type: application/json

{
  "title": "Example Session"
}

### Get sessions
GET {{base_url}}/api/sessions

### Delete session
DELETE {{base_url}}/api/sessions/4