apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: baam
      env: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: baam
        env: {{ .Release.Name }}
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: "true"
    spec:
      containers:
      - name: baam
        image: "ghcr.io/dcnick3/baam:{{ .Values.dockerTag }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
          - name: "DATABASE_HOST"
            value: {{ (include "baam.databaseHost" .) | quote }}
          - name: "DATABASE_PORT"
            value: {{ (include "baam.databasePort" .) | quote }}
          - name: "DATABASE_NAME"
            value: {{ (include "baam.databaseName" .) | quote }}
          - name: "DATABASE_USER"
            value: {{ (include "baam.databaseUser" .) | quote }}
          - name: "DATABASE_PASSWORD"
            valueFrom:
              secretKeyRef:
                key: password
                name: {{ (include "baam.databaseSecretName" .) }}
