apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}
  namespace: baam
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: baam
    env: {{ .Values.env }}
