on:
  push:
    branches:
      - master

name: Deploy to prod

# TODO: build container

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://baam.dcnick3.me
    steps:
      - uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 'Build container'
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: 'ghcr.io/dcnick3/baam:ref-${{ github.sha }}'
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 'Deploy'
        uses: 'glopezep/helm@v1.7.1'
        with:
          release: 'prod'
          namespace: 'baam'
          chart: 'deployment'
          helm: 'helm3'
          token: '${{ github.token }}'
          values: |
            domain: baam.dcnick3.me
            env: prod
            dockerTag: ref-${{ github.sha }}
            pullPolicy: Always
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
