on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]

name: Deploy

# TODO: build container

jobs:
  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened')
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
#        with:
#          driver: kubernetes
#          driver-opts: requests.cpu=6,requests.memory=4Gi

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v1

      - name: 'Build container'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: 'ghcr.io/dcnick3/baam:ref-${{ github.sha }}'
          cache-from: type=registry,ref=ghcr.io/dcnick3/baam:buildcache
          cache-to: type=registry,ref=ghcr.io/dcnick3/baam:buildcache,mode=max

  deploy-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    concurrency: prod
    environment:
      name: prod
      url: https://baam.dcnick3.me
    steps:
      - uses: actions/checkout@v1

      - name: 'Deploy to prod'
        uses: 'glopezep/helm@v1.7.1'
        with:
          release: prod
          namespace: baam
          chart: deployment
          helm: helm3
          token: ${{ github.token }}
          values: |
            domain: baam.dcnick3.me
            dockerTag: ref-${{ github.sha }}
          value-files: |
            deployment/values.yml
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

      # tell sentry we've got a new release
      - uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: dcnick3-services
          SENTRY_PROJECT: baam
        with:
          environment: 'production'

  deploy-pr:
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened')
    needs: build
    runs-on: ubuntu-latest
    concurrency: pr-${{ github.event.pull_request.number }}
    environment:
      name: pr-${{ github.event.pull_request.number }}
      url: https://pr-${{ github.event.pull_request.number }}.baam.dcnick3.me
    steps:
      - uses: actions/checkout@v1

      - name: 'Deploy a pr'
        uses: 'glopezep/helm@v1.7.1'
        with:
          release: pr-${{ github.event.pull_request.number }}
          namespace: baam
          chart: deployment
          helm: helm3
          token: ${{ github.token }}
          values: |
            domain: pr-${{ github.event.pull_request.number }}.baam.dcnick3.me
            dockerTag: ref-${{ github.sha }}
          value-files: |
            deployment/values.yml
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

  destroy-pr:
    if: github.event_name == 'pull_request' && (github.event.action == 'closed')
    runs-on: ubuntu-latest
    concurrency: pr-${{ github.event.pull_request.number }}

    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v1

      - name: 'Destroy a pr'
        uses: 'glopezep/helm@v1.7.1'
        with:
          release: pr-${{ github.event.pull_request.number }}
          namespace: baam
          chart: deployment
          helm: helm3
          token: ${{ github.token }}
          task: remove
          values: |
            domain: pr-${{ github.event.pull_request.number }}.baam.dcnick3.me
            dockerTag: ref-${{ github.sha }}
          value-files: |
            deployment/values.yml
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

      - uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: pr-${{ github.event.pull_request.number }}
          onlyRemoveDeployments: true