on:
  push:
    branches:
      - master
  pull_request:

name: Deploy

# TODO: build container

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build container'
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: 'ghcr.io/dcnick3/baam:ref-${{ github.sha }}'
          cache-from: type=registry,ref=ghcr.io/dcnick3/baam:buildcache
          cache-to: type=registry,ref=ghcr.io/dcnick3/baam:buildcache,mode=max

  deploy-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://baam.dcnick3.me
    steps:
      - uses: actions/checkout@v1

      - name: 'Deploy to prod'
        uses: 'glopezep/helm@v1.7.1'
        with:
          release: prod
          namespace: baam
          chart: deployment
          helm: helm3
          token: ${{ github.token }}
          values: |
            domain: baam.dcnick3.me
            env: prod
            dockerTag: ref-${{ github.sha }}
            pullPolicy: Always
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

  deploy-pr:
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: 'Deploy a pr'
        uses: 'glopezep/helm@v1.7.1'
        with:
          release: pr-${{ github.event.pull_request.number }}
          namespace: baam
          chart: deployment
          helm: helm3
          token: ${{ github.token }}
          values: |
            domain: pr-${{ github.event.pull_request.number }}.baam.dcnick3.me
            env: pr-${{ github.event.pull_request.number }}
            dockerTag: ref-${{ github.sha }}
            pullPolicy: Always
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

