on:
  push:
    branches:
      - master

name: Deploy to prod

# TODO: build container

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://baam.dcnick3.me
    steps:
      - uses: actions/checkout@v1

      - name: 'Deploy'
        uses: 'glopezep/helm@v1.7.1'
        with:
          release: 'prod'
          namespace: 'baam'
          chart: 'deployment'
          helm: 'helm3'
          token: '${{ github.token }}'
          values: |
            env: prod
          value-files: "[\"deployment/values.yml\", \"deployment/values.prod.yml\"]"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
