name: Deploy
on: ['deployment']

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'prod'
        namespace: 'baam'
        chart: 'deployment'
        token: '${{ github.token }}'
        values: |
          env: prod
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
