on: push

name: frontend

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Script
        working-directory: ./frontend
        run: |
          set -euxo pipefail
          npm install
          npx playwright install

          npm run lint
          npm run check

          npm run test
          npm run build

      # FIXME: deploy this shit instead of just pushing the artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: frontend/build
