on: push

name: frontend

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd frontend
      - name: Install dependencies
        run:
          npm install --global npx
          npm install
          npx playwright install
      - name: Lint
        run: |
          npm run lint
          npm run check
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build

      # FIXME: deploy this shit instead of just pushing the artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: frontend/.svelte-kit/output
